### ISSUE TITLE
misaligned circle content positions when using circle-through

### ISSUE THREAD

**Issue by AdiWeit** [johannes-wolf/cetz#300] opened 2023-10-27 10:31 UTC
When writing 
#cetz.canvas({
import cetz.draw: *
import cetz.angle: angle
circle-through((0, 0), (6, 0), (4, 3), stroke: red, name: "circ")
circle("circ.center", radius: 4, stroke: blue, name: "circ2")
// points of the circle
circle((0, 0), radius: .07)
circle((6, 0), radius: .07)
circle((4, 3), radius: .07)
// drawing content of the cricle
for point in ("top-left", "top-right", "top", "right", "left", "bottom-left", "bottom-right", "bottom", "center") {
  content("circ."+point, "1")
  content("circ2."+point, "2")
}
})
the content of the blue circle created using `circle(...)` is positioned just fine, but when using `circle-through(...)` (the red circle) it positions the content way too far towards the middle or am I missing something?
![grafik](https://github.com/johannes-wolf/cetz/assets/43521682/3ec813bf-f8b3-4185-97db-38675796e18d)

**Comment by fenjalien** [comment] 2023-10-27 11:20
This will be fixed in 0.2 but it is caused by `circle-through` calculating its anchors with the wrong radius. It'll be affected by the `radius` style key.

**Closed** 2023-11-11 16:38 UTC
Labels: bug :bug:, core:draw :pencil2:
