### ISSUE TITLE
Obscure line break in text under very specific conditions

### ISSUE THREAD

**Issue by linuxrider** [johannes-wolf/cetz#438] opened 2024-01-03 12:38 UTC
A line break is occurring under very specific conditions only with cetz 0.2.0.
The important conditions are: text font, text lang, justification.
Line break is present for `Terme` and `Termx` but not for `Terms` and `Termen`.
```typst
#import "cetz/0.2.0/src/lib.typ": canvas, plot, draw
// #import "@preview/cetz:0.1.2": canvas, plot, draw
#set page(width: auto, height: auto)

// important parameters
#set par(justify: true)
#set text(font: "Source Sans Pro", lang: "de")

#canvas(length: 1cm, {
      import draw: *
      content((0,0), "Terme")
      content((0,1), "Termx")
      content((0,2), "Terms")
      content((0,4), "Termen")
  }
)
```

**Comment by johannes-wolf** [comment] 2024-01-03 13:02
I can not reproduce the linebreaks on 0.2.0 with Typst 0.10.0:
![grafik](https://github.com/johannes-wolf/cetz/assets/519002/9e373357-4ece-4bbc-9487-3ec663cb2fd7)

**Comment by linuxrider** [comment] 2024-01-03 13:22
You are right. It only happens on `typst.app` (Typst compiler version: 70ca0d25).

**Comment by johannes-wolf** [comment] 2024-01-03 21:49
I guess using `justify: true` with cetz `content` only works if you use content with two points to span a content rect. I would suggest disabling justification when using cetz `content` elements.

**Comment by laurmaedje** [comment] 2024-02-07 12:56
> I can not reproduce the linebreaks on 0.2.0 with Typst 0.10.0 (70ca0d25)

The font in your screenshot is not Source Sans Pro, probably it isn't installed. It looks more like Linux Libertine due to silent fallback (I know ... warnings for that are coming).

**Comment by johannes-wolf** [comment] 2024-02-07 13:24
> > I can not reproduce the linebreaks on 0.2.0 with Typst 0.10.0 (70ca0d25)
> 
> The font in your screenshot is not Source Sans Pro, probably it isn't installed. It looks more like Linux Libertine due to silent fallback (I know ... warnings for that are coming).

I have the font installed. But you are right, it seems it does not get used.

**Comment by johannes-wolf** [comment] 2024-02-07 13:27
> > I can not reproduce the linebreaks on 0.2.0 with Typst 0.10.0 (70ca0d25)
> 
> The font in your screenshot is not Source Sans Pro, probably it isn't installed. It looks more like Linux Libertine due to silent fallback (I know ... warnings for that are coming).

You are right… the fonts are installed, but they are called "Source Sans 3" on Fedora.
I can now reproduce the issue:

![grafik](https://github.com/johannes-wolf/cetz/assets/519002/170da434-bc8f-40a6-a82d-e6541fec66a1)

**Comment by johannes-wolf** [comment] 2024-02-07 13:40
It is a rounding issue I fixed by rounding the measured sizes up. See linked PR.

**Closed** 2024-02-08 11:36 UTC
Labels: bug :bug:, core:draw :pencil2:
