### ISSUE TITLE
content misalignment

### ISSUE THREAD

**Issue by AdiWeit** [johannes-wolf/cetz#296] opened 2023-10-26 20:06 UTC
Like seen in the user manual (first graphic) and also in my little code example (second graphic), the content, meaning p_1, p_2, ..., is colliding with the lines/graph. It would be great if it would go a little bit more away from the point it's referring to. Maybe there's an option  that I'm missing but I think in that case the manual should change. To make clear what I mean the last image is what it should look like (I created the graph using Latex tikz)
![grafik](https://github.com/typst/packages/assets/43521682/bb3814b1-9092-47a7-ab45-74d297ae7efa)
![grafik](https://github.com/typst/packages/assets/43521682/23fd1927-36a0-415e-b58c-a06d25c0b290)
![grafik](https://github.com/typst/packages/assets/43521682/7efb24e0-0282-423f-9a64-4a641ddff3f0)

**Comment by johannes-wolf** [comment] 2023-10-26 21:28
Yes, the example of the manual is not good.

Here is your triangle with `content: (padding: .1)` set:
```typst
#import "@preview/cetz:0.1.2": canvas, draw

#canvas(length: 1cm, {
  import draw: *
  set-style(content: (padding: .1))
  line((0,0), (6,0), (4,3), close: true, name: "Test")
  content("Test.bottom-left", $ A $, anchor: "right")
  content("Test.bottom-right", $ B $, anchor: "left")
  content("Test.end", $ C $, anchor: "bottom")
})
```

Showing as:
![grafik](https://github.com/johannes-wolf/cetz/assets/519002/f60f4ba8-d965-41e4-a1c4-30db2fe03a40)

**Comment by AdiWeit** [comment] 2023-10-27 06:17
`set-style(content: (padding: .5))` also moves the triangle. Is that supposed to happen? :thinking: 
The first picture is with set-style, the second without
![grafik](https://github.com/johannes-wolf/cetz/assets/43521682/192752f1-a6b8-45f0-8d48-4d08c7916c8e)
![grafik](https://github.com/johannes-wolf/cetz/assets/43521682/f48ed0ea-594e-4040-8e91-d555bfaac34b)

**Comment by AdiWeit** [comment] 2023-10-27 06:17
sry, wrong click :laughing:

**Comment by johannes-wolf** [comment] 2023-10-27 08:50
The triangle is moved, because the canvas resizes itself to show all elemenst. So the negative x of the "A" becomes "0" and theirfore everything gets moved to the right. This is expected behavior. The relative positioning stays correct.

**Comment by johannes-wolf** [comment] 2023-10-30 00:28
Closing: Manual example has been improved.

**Closed by johannes-wolf** 2023-10-30 00:28 UTC
Labels: documentation
